apiVersion: apps/v1
kind: Deployment

metadata:
  name: devsecopsapp

spec:
  replicas: 1

  selector:
    matchLabels:
      app: devsecopsapp

  template:
    metadata:
      labels:
        app: devsecopsapp

    spec:
      containers:
        - name: devsecopsapp
          image: ghcr.io/aissatou-samba15/devsecopsapp:latest

          ports:
            - containerPort: 8080

          env:
            - name: ASPNETCORE_URLS
              value: "http://+:8080"

            - name: ASPNETCORE_ENVIRONMENT
              value: "Development"