name: CI DevSecOpsApp

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurer les dépendances
        run: dotnet restore DevSecOpsApp.slnx

      - name: Analyser les vulnérabilités des dépendances (SCA)
        run: dotnet list DevSecOpsApp.slnx package --vulnerable --include-transitive

      - name: Compiler l'application
        run: dotnet build DevSecOpsApp.slnx --no-restore --configuration Release

      - name: Exécuter les tests
        run: dotnet test DevSecOpsApp.slnx --no-build --configuration Release

  security-analysis:
    name: Analyse SAST avec CodeQL
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Initialiser CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: csharp

      - name: Compiler pour CodeQL
        uses: github/codeql-action/autobuild@v3

      - name: Analyser le code
        uses: github/codeql-action/analyze@v3